services:
  - type: web
    name: 3d-ar-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: TRIPO_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: WEB_SERVER_HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 