version: 1
disable_existing_loggers: false

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: data/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  mcp_server_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: data/logs/mcp_server.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  web_server_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: data/logs/web_server.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  api_calls_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: data/logs/api_calls.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: data/logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  mcp_server:
    level: DEBUG
    handlers: [console, mcp_server_file, error_file]
    propagate: false
  
  web_server:
    level: DEBUG
    handlers: [console, web_server_file, error_file]
    propagate: false
  
  api_client:
    level: INFO
    handlers: [console, api_calls_file, error_file]
    propagate: false
  
  model_generator:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false
  
  file_manager:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false
  
  format_converter:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file] 